IF 
EXISTS(SELECT 1 FROM sys.procedures WHERE Name = 'GetFastSalePrice')
AND
EXISTS(SELECT 1 FROM sys.procedures WHERE Name = 'SaveTaxTrans')
AND
EXISTS(SELECT 1 FROM sys.procedures WHERE Name = 'StockInsertStock')
AND 
EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_TYPE='BASE TABLE' AND TABLE_NAME='Item')
AND 
EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_TYPE='BASE TABLE' AND TABLE_NAME='ItemNames')
AND 
EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_TYPE='BASE TABLE' AND TABLE_NAME='PartyAddress')
AND 
EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_TYPE='BASE TABLE' AND TABLE_NAME='Salesman')
AND 
EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_TYPE='BASE TABLE' AND TABLE_NAME='Customer')
AND
EXISTS(SELECT 1 FROM   sys.objects WHERE  OBJECT_ID = OBJECT_ID('dbo.CustomerSales') AND Type_Desc = 'VIEW')
BEGIN
    SELECT 'true' AS result
END
ELSE
BEGIN
    SELECT 'false' AS result
END