IF 
	EXISTS(SELECT 1 FROM sys.procedures WHERE Name = 'Grh_Actualiza_Processados')
AND
	EXISTS(SELECT 1 FROM sys.procedures WHERE Name = 'Std_cls_ProcessoEstados')
AND
	EXISTS(SELECT 1 FROM sys.procedures WHERE Name = 'Gce_GetPrecoVenda')
AND 
	EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_TYPE='BASE TABLE' AND TABLE_NAME='Tbl_Clientes')
AND 
	EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_TYPE='BASE TABLE' AND TABLE_NAME='Mov_Venda_Lin')
AND 
	EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_TYPE='BASE TABLE' AND TABLE_NAME='Mov_Venda_Cab')
AND 
	EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_TYPE='BASE TABLE' AND TABLE_NAME='Tbl_Gce_Familias')
AND 
	EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_TYPE='BASE TABLE' AND TABLE_NAME='Tbl_Taxas_Iva')
AND
	EXISTS(SELECT 1 FROM   sys.objects WHERE  OBJECT_ID = OBJECT_ID('dbo.view_Inte_Clientes') AND Type_Desc = 'VIEW')
BEGIN
    SELECT 'true' AS result
END
ELSE
BEGIN
    SELECT 'false' AS result
END