IF 
EXISTS(SELECT 1 FROM sys.procedures WHERE Name = 'SP_u_Kapps_Dossiers')
AND
EXISTS(SELECT 1 FROM sys.procedures WHERE Name = 'SP_u_Kapps_DocDossInternIVAs')
AND
EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_TYPE='BASE TABLE' AND TABLE_NAME='u_KApps_DossierLin')
AND 
EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_TYPE='BASE TABLE' AND TABLE_NAME='u_Kapps_Parameters')
AND 
EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_TYPE='BASE TABLE' AND TABLE_NAME='u_KApps_Log')
AND 
EXISTS(SELECT 1 FROM   sys.objects WHERE  OBJECT_ID = OBJECT_ID('dbo.v_Kapps_Documents') AND Type_Desc = 'VIEW')
BEGIN
    SELECT 'true' AS result
END
ELSE
BEGIN
    SELECT 'false' AS result
END
